### PR TITLE
Add support for jackson 2.12

### PR DESCRIPTION
**Pull request by ghillairet**
Fix for #6

### CODE REVIEW

**Comment by juergen-albert** [comment]
I gave it a try and it seems to do the job. @ghillairet thanks heaps for fixing this!

**Comment by PhilippeBrossel** [comment]
I tried it out, and your fix solves the issue for me. 
@ghillairet : Many thanks for this great tool !
Btw, I had to add a `/META-INF/MANIFEST.MF` with an adequate `Export-Package` to be able to access the packages `org.emfjson.jackson.*` from my plugin-projects 
(Was just to circumvent the warning `This plug-in does not have an OSGI bundle manifest.`)
**Is there a better way to do that or can you give me a hint of what I'm doing wrong ?**

**Comment by debovema** [comment]
Can someone merge this ?

**Review by martin-fleck-at — APPROVED** [review]
Thank you very much for the fix, @ghillairet . Btw, we are in the process of setting up the build infrastructure for this so it might not be immediately consumable right now.

**Pull request merged**
